bof:
    build: ./bof
    volumes:
        - ./bof/home:/home/bof:ro
        - ./bof/xinetd:/etc/xinetd.d/xinetd:ro
    ports:
        - "10100:4597"
    expose:
        - "4597"

bof2:
    build: ./bof2
    volumes:
        - ./bof2/home:/home/bof2:ro
        - ./bof2/xinetd:/etc/xinetd.d/xinetd:ro
    ports:
        - "10105:4597"
    expose:
        - "4597"

luck:
    build: ./luck
    volumes:
        - ./luck/home:/home/luck:ro
        - ./luck/xinetd:/etc/xinetd.d/xinetd:ro
    ports:
        - "10101:4597"
    expose:
        - "4597"

luck2:
    build: ./luck2
    volumes:
        - ./luck2/home:/home/luck2:ro
        - ./luck2/xinetd:/etc/xinetd.d/xinetd:ro
    ports:
        - "10102:4597"
    expose:
        - "4597"

ysb:
    build: ./sb
    volumes:
        - ./sb/yuawn:/home/ysb:ro
        - ./sb/xinetd:/etc/xinetd.d/xinetd:ro
    ports:
        - "10103:4597"
    expose:
        - "4597"

simpleecho:
    build: ./simpleecho
    volumes:
        - ./simpleecho/maps:/home/simpleecho:ro
        - ./simpleecho/xinetd:/etc/xinetd.d/xinetd:ro
    ports:
        - "10104:4597"
    expose:
        - "4597"
